### ISSUE TITLE
Add MiniMessage compatibility

### ISSUE THREAD

**Issue by SorkoPiko** [aternosorg/motdgg-bukkit#5]
Hey, I found your tool recently and I really like it! However, I use [AdvancedServerList](https://modrinth.com/plugin/advancedserverlist) because it supports random MOTDs, and it doesn't use the native `§a` format, it instead uses MiniMessage. It would be great if you could add MiniMessage output as well as normal output, as then more people would be able to use it. Thanks!

**Comment by JulianVennen** [comment]
motd.gg is designed around compatibility with vanilla. The vanilla formatting codes are supported by every Minecraft server software.

Mini-Message offers some additional features but we don't want to add the additional complexity of having some formatting that only works on a specific server software.

**Comment by SorkoPiko** [comment]
OK, I just thought there could be a menu at the top of "Get your MOTD" area, where you can select between vanilla and MiniMessage. MiniMessage compatibility would not be hard; for example, `§6` converts to `<gold>`, the only real difficulty would be to make sure they are nested properly. However, I understand that you are trying to make a vanilla tool, so if this won't be added, it is totally understandable. Thanks anyway!

**Comment by Andre601** [comment]
This in all honesty sounds like an excuse.

Vanilla exists, but lets not kid ourself here. The majority uses either modded or plugin servers.

The MiniMessage support would be just a button that gives a slightly different output, so I can't see the issue here of making it.

Nobody asks for it to be the default. Just as an alternative.

MiniMessage becomes a standard for more and more people. And just because vanilla doesn't use it doesn't mean it's bad to add support.

**Comment by matthi4s** [comment]
What's the use case for this? We won't be able to support any additional features of Minimessage since that would mean a major rewrite of our editor. Using this plugin, you will just have the same MOTD in the end.

**Comment by Andre601** [comment]
> What's the use case for this? We won't be able to support any additional features of Minimessage since that would mean a major rewrite of our editor. Using this plugin, you will just have the same MOTD in the end. 

Support for plugins that support minimessage while not supporting legacy?
Also, yes, a majority of MM features can't be used.
Tho there is support for translatables. Every key in mc can be added to the MOTD, which isn't doable with just legacy.

Also, there are these additional benefits:

 - Easier to read colours. A complete new user may not know what `&1` means (don't have the paragraph symbol on mobile) or the unicode thing (`\u...`), while `<dark_blue>` gives an idea.
- Better hex colours. Instead of a random mess like `&x&r&r&g&g&b&b` would it be `<#rrggbb>` which is more readable.
- Gradients! Just `<gradient:#rrggbb:#rrggbb>` and you get a gradient matching the provided text. And don't get me started on the nightmare that is making gradients in the legacy format...

**Comment by matthi4s** [comment]
I get the general benefits of Minimessage, but motd.gg currently does not support hex colors and therefore also no gradients like that.

So you want to be able to generate a motd on motd.gg and then paste the output in a different motd plugin?

**Comment by RealmKebab** [comment]
(i know my comment isn't needed)
https://webui.advntr.dev/ <- amazing website for creating whatever with minimessage

**Comment by Andre601** [comment]
> (i know my comment isn't needed) https://webui.advntr.dev/ <- amazing website for creating whatever with minimessage

That one in particular lacks features like centering the text, which apparently a lot of people want...

**Comment by RealmKebab** [comment]
> > (i know my comment isn't needed) https://webui.advntr.dev/ <- amazing website for creating whatever with minimessage
> 
> That one in particular lacks features like centering the text, which apparently a lot of people want...

im sure minimessage doesn't have support for centering text,
which if they did; then they would actually include it (as a button)

**+** add some type of symbol like how motd.gg does it and boom, you have centered text

https://docs.advntr.dev/minimessage/format.html

**Comment by RealmKebab** [comment]
as you can see, i copied the funny symbol from motd.gg and turned it into a minimessage
![image](https://github.com/aternosorg/motdgg-bukkit/assets/73048123/2645ce77-307c-4e9b-acc3-194484d025cb)
